# Generated by Django 4.2.5 on 2024-06-12 23:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Point",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                (
                    "id_number",
                    models.CharField(blank=True, default="", max_length=20, null=True),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MASCULINO", "masculino"),
                            ("FEMENINO", "femenino"),
                            ("OTRO", "otro"),
                        ],
                        default="",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default=" ", max_length=254, null=True
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, default="", max_length=20, null=True),
                ),
                (
                    "address",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "validate_ticket",
                    models.CharField(
                        blank=True, default="", max_length=20, null=True, unique=True
                    ),
                ),
            ],
        ),
    ]
