# Generated by Django 4.2.5 on 2024-06-15 01:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("points", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="point",
            name="pack",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
    ]
