# Generated by Django 4.2.5 on 2024-06-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("points", "0002_point_pack"),
    ]

    operations = [
        migrations.AddField(
            model_name="point",
            name="pay_money",
            field=models.CharField(blank=True, default="", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="point",
            name="statusPayment",
            field=models.CharField(
                blank=True,
                choices=[("PENDING", "pending"), ("PAID", "paid")],
                default="",
                max_length=255,
                null=True,
            ),
        ),
    ]
