# Generated by Django 4.2.5 on 2024-06-16 00:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("points", "0003_point_pay_money_point_statuspayment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="point",
            old_name="statusPayment",
            new_name="status_payment",
        ),
    ]
