# Generated by Django 4.2.5 on 2024-06-16 01:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("points", "0004_rename_statuspayment_point_status_payment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="point",
            name="status_payment",
        ),
    ]
