# Generated by Django 4.2.5 on 2024-07-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("points", "0005_remove_point_status_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="point",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
