# Generated by Django 4.2.5 on 2024-07-05 00:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("points", "0006_point_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="point",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
