# Generated by Django 4.2.5 on 2024-07-05 00:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("points", "0008_point_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="point",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="point",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
