# Generated by Django 4.2.5 on 2024-07-05 01:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("points", "0009_remove_point_updated_at_alter_point_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="point",
            name="update_history",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="point",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
