# Generated by Django 4.2.5 on 2024-07-05 01:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("points", "0010_point_update_history_point_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="point",
            name="updated_at",
        ),
    ]
