# Generated by Django 4.2.5 on 2024-07-05 02:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("points", "0011_remove_point_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="point",
            name="update_history",
        ),
    ]
