# Generated by Django 4.2.5 on 2024-07-05 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pays", "0001_initial"),
        ("points", "0012_remove_point_update_history"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="point",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="point",
            name="pay_money",
        ),
        migrations.AddField(
            model_name="point",
            name="pay",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="points",
                to="pays.pay",
            ),
        ),
    ]
