# Generated by Django 4.2.5 on 2024-07-05 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pays", "0001_initial"),
        ("points", "0013_remove_point_created_at_remove_point_pay_money_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="point",
            name="pay",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pays.pay",
            ),
        ),
    ]
