# Generated by Django 4.2.5 on 2024-07-06 01:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("points", "0014_alter_point_pay"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="point",
            name="pay",
        ),
        migrations.AddField(
            model_name="point",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="point",
            name="pay_money",
            field=models.CharField(blank=True, default="", max_length=20, null=True),
        ),
    ]
