# Generated by Django 4.2.5 on 2024-07-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("points", "0015_remove_point_pay_point_created_at_point_pay_money"),
    ]

    operations = [
        migrations.AlterField(
            model_name="point",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
