# Generated by Django 4.2.5 on 2024-07-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("points", "0017_alter_point_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="point",
            name="created_at",
            field=models.DateTimeField(null=True),
        ),
    ]
