# Generated by Django 4.2.5 on 2024-07-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("points", "0019_alter_point_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="point",
            name="salesperson",
            field=models.CharField(
                blank=True,
                choices=[
                    ("diana gómez", "DIANA GÓMEZ"),
                    ("brayan realpe", "BRAYAN REALPE"),
                    ("janeth muñoz", "JANETH MUÑOZ"),
                    ("marco f. fernández", "MARCO F. FERNÁNDEZ"),
                    ("jhonny figueroa", "JHONNY FIGUEROA"),
                    ("jaime mayorga", "JAIME MAYORGA"),
                    ("fabián fernández", "FABIÁN FERNÁNDEZ"),
                    ("jorge reyes", "JORGE REYES"),
                ],
                default="",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="point",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MASCULINO", "masculino"),
                    ("FEMENINO", "femenino"),
                    ("OTRO", "otro"),
                ],
                default="",
                max_length=50,
                null=True,
            ),
        ),
    ]
