# Generated by Django 4.2.5 on 2024-07-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("points", "0020_point_salesperson_alter_point_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="point",
            name="salesperson",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
    ]
