# Generated by Django 4.2.5 on 2024-07-18 05:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("points", "0021_alter_point_salesperson"),
    ]

    operations = [
        migrations.AlterField(
            model_name="point",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
