# Generated by Django 4.2.5 on 2024-07-10 23:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_activity",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
