# Generated by Django 4.2.5 on 2024-06-12 01:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Codeqr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_ticket", models.CharField(default="", max_length=4)),
                ("number_one", models.CharField(max_length=4)),
                ("number_two", models.CharField(max_length=4)),
                ("image_qr", models.ImageField(default="", upload_to="qr")),
            ],
        ),
    ]
