# Generated by Django 4.2.5 on 2025-06-11 01:09

from django.db import migrations, models
import django.db.models.deletion
import meetings.models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='start_datetime',
        ),
        migrations.CreateModel(
            name='MeetingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('audio_file', models.FileField(blank=True, null=True, upload_to=meetings.models.upload_to_audio)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='meetings.meeting')),
            ],
        ),
    ]
