# Generated by Django 4.2.5 on 2025-06-12 15:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_remove_meeting_audio_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='meetingsession',
            name='acta_status',
            field=models.CharField(choices=[('pending', 'En proceso'), ('generated', 'Acta generada'), ('error', 'Error al generar acta')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='meetingsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetingsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
