# Generated by Django 4.2.5 on 2025-06-12 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_meetingphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='cover_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_cover_for_meetings', to='meetings.meetingphoto'),
        ),
    ]
