# Generated by Django 4.2.5 on 2025-06-14 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0005_meeting_cover_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingSessionActaVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('content_html', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('word_file', models.FileField(blank=True, null=True, upload_to='meetings/actas/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acta_versions', to='meetings.meetingsession')),
            ],
            options={
                'ordering': ['-version', '-created_at'],
            },
        ),
    ]
