# Generated by Django 4.2.5 on 2025-07-02 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0008_remove_meetingsessionactaversion_comite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingsessionactaversion',
            name='numero',
        ),
    ]
